name: Calling GH Actions
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
    - id: call1
    - name : Call GH Action 
      uses: actions/hello-world-javascript-action@v1
      with:
        who-to-greet: Raminder
    - name : Display output
      run: echo "{{ steps.call1.outputs.time }}"