name: using strategy

on: [push]

jobs:
  node-version:
    strategy:
      matrix:
        node-version: [6,8,10]
    runs-on: ubuntu-latest
    steps:
    - name: check 1
      run: node -v
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: check 2
      run: node -v
