name: Workflow-Testing-Strategy
on: [push]
jobs:
  node-version:
    strategy:
      matrix:
        node-version: [6,8,10]
    runs-on: ubuntu-latest
    steps:
      - name: check earlier version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          continue-on-error: true
      - name: check later version
        run: node -v